
package publishservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 * 			Ueber das WE Highscore Service koennen Ergebnisse des WE Mensch Aergere Dich Nicht Spiels auf das WE Highscore Board gepostet werden
 * 		
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PublishHighScoreService", targetNamespace = "http://big.tuwien.ac.at/we/highscore", wsdlLocation = "http://playground.big.tuwien.ac.at:8080/highscore/PublishHighScoreService?wsdl")
public class PublishHighScoreService
    extends Service
{

    private final static URL PUBLISHHIGHSCORESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(publishservice.PublishHighScoreService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = publishservice.PublishHighScoreService.class.getResource(".");
            url = new URL(baseUrl, "http://playground.big.tuwien.ac.at:8080/highscore/PublishHighScoreService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://playground.big.tuwien.ac.at:8080/highscore/PublishHighScoreService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PUBLISHHIGHSCORESERVICE_WSDL_LOCATION = url;
    }

    public PublishHighScoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublishHighScoreService() {
        super(PUBLISHHIGHSCORESERVICE_WSDL_LOCATION, new QName("http://big.tuwien.ac.at/we/highscore", "PublishHighScoreService"));
    }

    /**
     * 
     * @return
     *     returns PublishHighScoreEndpoint
     */
    @WebEndpoint(name = "PublishHighScorePort")
    public PublishHighScoreEndpoint getPublishHighScorePort() {
        return super.getPort(new QName("http://big.tuwien.ac.at/we/highscore", "PublishHighScorePort"), PublishHighScoreEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublishHighScoreEndpoint
     */
    @WebEndpoint(name = "PublishHighScorePort")
    public PublishHighScoreEndpoint getPublishHighScorePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://big.tuwien.ac.at/we/highscore", "PublishHighScorePort"), PublishHighScoreEndpoint.class, features);
    }

}
